services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp:/tmp  # For temporary file processing
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - LLM_BACKEND=llama_cpp
      - LLM_STRICT_MODE=true
      - PYTHONUNBUFFERED=1
      - LLM_API_URL=http://llama-cpp:8080/completion
      - HOST_RAM_GB=32
      - HOST_CPU_COUNT=12
      - CUDA_VISIBLE_DEVICES=0  # Enable GPU for backend
    depends_on:
      - qdrant
      - llama-cpp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  llama-cpp:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    platform: linux/amd64  # Force AMD64 for llama-cpp
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    environment:
      - MODEL_NAME=${MODEL_NAME:-qwen2-7b-instruct-q4_k_m.gguf}
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
    command: >
      --model /models/${MODEL_NAME:-qwen2-7b-instruct-q4_k_m.gguf}
      --host 0.0.0.0
      --port 8080
      --ctx-size 4096
      --threads 16
      --n-gpu-layers 35
      --batch-size 512
      --n-predict 128
      --repeat-penalty 1.1
      --temp 0.7
      --top-p 0.9
      --top-k 40
      --mirostat 2
      --mirostat-tau 5.0
      --mirostat-eta 0.1
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/amd64  # Force AMD64 for Qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # HTTP API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6334
      - QDRANT__SERVICE__GRPC_PORT=6333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6334/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # tusd service for chunked file uploads
  tusd:
    image: tusproject/tusd:latest
    platform: linux/amd64
    ports:
      - "1080:1080"
    volumes:
      - ./data/uploads:/data
    environment:
      - TUSD_DATA_DIR=/data
    command: ["-upload-dir", "/data", "-host", "0.0.0.0", "-port", "1080", "-hooks-http", "http://backend:8000/enhanced-upload/tus-hooks"]
    restart: unless-stopped
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:1080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    platform: linux/amd64  # Force AMD64 for Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Optional: Add Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64  # Force AMD64 for Grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  qdrant_data:
  prometheus_data:
  grafana_data: 