global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RAG Backend API
  - job_name: 'rag-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Qdrant Vector Database
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6334']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Llama-cpp Server
  - job_name: 'llama-cpp'
    static_configs:
      - targets: ['llama-cpp:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s 